"""update schema

Revision ID: 63fbc60aedc2
Revises: b106d2b18846
Create Date: 2026-04-26 12:43:15.356020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fbc60aedc2'
down_revision: Union[str, Sequence[str], None] = 'b106d2b18846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('country_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'country_code')
    # ### end Alembic commands ###
